version: '3.8'
services:
  app:
    container_name: react-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
      - ignore:/usr/app/node_modules/
volumes:
  ignore: